version: '3'
services:
  postgres-service:
    image: postgres:latest
    container_name: crud-spring-boot-rest-api
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
#    volumes:
#      - /var/lib/postgres
#      - ./dbscripts/postgres:/docker-entrypoint-initdb.d